---
title: "ReadMe for 'Human Activity Recognition Using Smartphones Dataset'"
author: "Cody"
date: "2023-06-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Human Activity Recognition Using Smartphones Dataset
Version 1.0

Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
Smartlab - Non Linear Complex Systems Laboratory
DITEN - Universit? degli Studi di Genova.
Via Opera Pia 11A, I-16145, Genoa, Italy.
<activityrecognition@smartlab.ws>
www.smartlab.ws

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 

# For each record it is provided:
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

# The dataset includes the following files:
- 'ReadMe.RMD'

- 'ReadMe.pdf': PDF of the ReadMe R markdown file

- 'CodeBook.Rmd': 

- 'CodeBook.pdf': PDF of the CodeBook R markdown file

- 'run_analysis.R': Script that takes the tidy's the 

- 'training_set.txt': File that combines 'X_train.txt', 'y_train.txt', and 'subject_train.txt' to the tidy specifications defined by the course "Getting and Cleaning Data" project specifications.

- 'testing_set.txt': File that combines 'X_test.txt', 'y_test.txt', and 'subject_train.txt' to the tidy specifications defined by the course "Getting and Cleaning Data" project specifications.

- 'training_set_averages.txt': File that uses the 'training_set.txt' to calculate the average of both the mean and standard deviation for acceleration data across subject and activity

- 'testing_set_averages.txt': File that uses the 'testing_set.txt' to calculate the average of both mean and standard deviation for acceleration data across subject and activity

- 'UCI HAR Dataset/README.txt': README that describes the original dataset 

- 'UCI HAR Dataset/features_info.txt': Shows information about the variables used on the feature vector.

- 'UCI HAR Dataset/features.txt': List of all features.

- 'UCI HAR Dataset/activity_labels.txt': Links the class labels with their activity name.

- 'UCI HAR Dataset/train/X_train.txt': Training set.

- 'UCI HAR Dataset/train/y_train.txt': Training labels.

- 'UCI HAR Dataset/test/X_test.txt': Test set.

- 'UCI HAR Dataset/test/y_test.txt': Test labels.

# The following files are available for the train and test data. Their descriptions are equivalent. 
- 'UCI HAR Dataset/train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 

# Notes: 
- Features are normalized and bounded within [-1,1].
- Each feature vector is a row on the text file.

For more information about this dataset contact: <activityrecognition@smartlab.ws>

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
